### ISSUE TITLE
Als Modellierer möchte ich eine IFrame URL vom document-signing-service anfragen können

### ISSUE THREAD

**Issue by dominikhorn93** [Miragon/digiwf-core#4]
**Beschreibung**
Um, Dokumente zu unterschreiben, wird eine Integrationskomponente benötigt, die einen S3 Pfad entgegennimmt und eine S3-URL und signing URL zurückgegeben.

**TODOs**
- Integrationsservice "digiwf-signing-integration" aufsetzen
  - Der Integrationsservice wird synchron über REST direkt aus der Frontend Komponente aufgerufen
- CreateSigningRequestUseCase umsetzen
  - Input:
    -  s3-pfad: Pfad in dem das Dokument liegt
  - Output:
    - ~~s3-url: PUT url, um Dokument zu laden und zu updaten~~
    - signing-url: url des signing service
- ~~Prozess umsetzen~~
  - ~~Start mit Upload -> Signing Integration -> User Task, der die Werte in einem Objekt anzeigt  + das Dokument zum Download anbietet~~

**Comment by lmoesle** [comment]
@dominikhorn93 Ich habe eine Frage zum Naming der Inputs und Outputs: Verstehe ich das richtig, dass der Service als Input einen Pfad in einem S3 Bucket bekommt (z.B. path/to/my/file) und dann eine Presigned Url (PUT) und die Url des signing services zurückgibt?

**Comment by dominikhorn93** [comment]
@lmoesle genau so ist es 👍 Wir wollen die URL des Signing Services nicht im Prozess konfigurieren. Man könnte das erzeugen der S3 URL auch den S3 Service direkt machen lassen und 2 Integrationen nutzen. Ich finde das gehört aber in den gleichen UseCase. Im DigiWF Team hatten wir meines Wissens nach darüber auch diskutiert, dass wir das bspw. bei Mail usw. ändern möchten oder?

**Comment by lmoesle** [comment]
Passt, dann ruf ich die S3 Integration synchron auf. Dann wird der Prozess auch etwas kleiner. Darüber wurde mal diskutiert, aber es ist noch nicht wirklich umgesetzt worden

**Comment by dominikhorn93** [comment]
Stimmt, aber wenn das 734 Ticket aus DigiWF umgesetzt ist, müsste es gehen oder?

**Comment by lmoesle** [comment]
Das geht auch so schon. 734 brauchen wir wenn wir eine Custom S3 Integration verwenden wollen. Das würde ich aber erstmal für den Showcase ausklammern
