### ISSUE TITLE
Als Benutzer möchte ich in einem Formularfeld Dokumente unterschreiben können

### ISSUE THREAD

**Issue by dominikhorn93** [Miragon/digiwf-core#5]
**Beschreibung**
Im Formular soll doXisign integriert werden, um Dokumente zu unterzeichnen.

Die Komponente erhält den Pfad zum Dokument im S3 Storage und holt sich über Http Rest Requests eine Presigned Url (S3 Integration) und die signingUrl (Signing Integration).

**TODOs**
- Komponente erstellen, die einen Modal öffnet, indem doXisign als iFrame eingebunden wird
- Komponente hat ein Objekt als Value, das aus 2 Properties besteht. signingUrl + s3-url
- z.T. Logik vom Multifile Input Feld übernehmen, um presigned Urls zu erhalten

**Offene Punkte**
- verifizieren, wie die Schnittstelle im IFRAME zu doXisign umzusetzen ist
  - S3 URL und doXisign übernimmt den Download und Upload
  - oder die Wrapper Komponente übernimmt den Download und Upload

**Comment by lmoesle** [comment]
**Aktueller Stand**

- Signing Komponente ist erstellt
- Signing Komponente holt sich presigned Urls von der S3 Integration und eine singing Url von der Singing Integration
- Es gibt einen kleinen Beispielprozess (Name: DoXisign)

**Noch offen**

- Die Anbindung von DoXisign/DoXiview in einem Iframe
- Dateien zwischen UnD Service und S3 syncen (up & download)
