### ISSUE TITLE
Testdaten für Showcase erweitern

### ISSUE THREAD

**Issue by dominikhorn93** [Miragon/digiwf-core#6]
**Beschreibung**
Für den Showcase werden Testdaten für 3 verschiedenen Benutzer benötigt.
Momentan existiert nur johndoe.

**TODO**
- Testuser definieren
- Testuser in keycloak + ldap erweitern

**Comment by lmoesle** [comment]
Es reichen vermutlich die 2 bestehenden Testuser Johndoe und Janedoe aus
